// Code generated by DeepSeek V4 Pro (AI). DO NOT EDIT.
// Generated at: 2026-06-13

package colorfmt

import (
	"bytes"
	"fmt"
	"io"
	"strings"
	"testing"
	"time"

	"github.com/BOOMfinity/golog/v3/gcore"
)

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

func testLogger(t *testing.T, cfg ...Config) (*gcore.Logger, *bytes.Buffer) {
	t.Helper()
	buf := &bytes.Buffer{}
	cfg2 := Config{}
	if len(cfg) > 0 {
		cfg2 = cfg[0]
	}
	cfg2.Base.StandardOutput = buf
	log := gcore.Init("test", Init(cfg2))
	return log, buf
}

func benchLogger(b *testing.B, cfg Config) *gcore.Logger {
	b.Helper()
	cfg.Base.StandardOutput = io.Discard
	return gcore.Init("test", Init(cfg))
}

// ---------------------------------------------------------------------------
// Init
// ---------------------------------------------------------------------------

func TestInit_ReturnsFormatter(t *testing.T) {
	f := Init()
	if f == nil {
		t.Fatal("Init returned nil")
	}
}

func TestInit_DefaultTimeFormat(t *testing.T) {
	log, buf := testLogger(t)
	log.Info().Msg("hello")
	out := buf.String()
	today := time.Now().Format("02.01.2006")
	if !strings.Contains(out, today) {
		t.Errorf("expected default date format in output: %s", out)
	}
}

func TestInit_CustomTimeFormat(t *testing.T) {
	log, buf := testLogger(t, Config{Base: gcore.Config{TimeFormat: "15:04:05"}})
	log.Info().Msg("hello")
	out := buf.String()
	if !strings.Contains(out, time.Now().Format("15:04:")) {
		t.Errorf("expected custom time in output: %s", out)
	}
}

// ---------------------------------------------------------------------------
// output: message lengths
// ---------------------------------------------------------------------------

func TestOutput_ShortMessage(t *testing.T) {
	log, buf := testLogger(t)
	log.Info().Msg("x")
	if !strings.Contains(buf.String(), " -> x") {
		t.Errorf("expected short message: %s", buf.String())
	}
}

func TestOutput_LongMessage(t *testing.T) {
	msg := strings.Repeat("abcdefghij", 200)
	log, buf := testLogger(t)
	log.Info().Msg(msg)
	if !strings.Contains(buf.String(), msg) {
		t.Error("expected long message in output")
	}
}

func TestOutput_UnicodeMessage(t *testing.T) {
	log, buf := testLogger(t)
	log.Info().Msg("żółć 日本語 🚀")
	out := buf.String()
	for _, s := range []string{"żółć", "日本語", "🚀"} {
		if !strings.Contains(out, s) {
			t.Errorf("expected unicode %q: %s", s, out)
		}
	}
}

// ---------------------------------------------------------------------------
// output: attributes
// ---------------------------------------------------------------------------

func TestOutput_NoAttributes(t *testing.T) {
	log, buf := testLogger(t)
	log.Info().Msg("plain")
	out := buf.String()
	if strings.Contains(out, "env(") {
		t.Error("should not have attribute section")
	}
}

func TestOutput_SingleAttribute(t *testing.T) {
	log, buf := testLogger(t)
	log.Info().Attr("key", "val").Msg("test")
	out := buf.String()
	if !strings.Contains(out, "key(val)") {
		t.Errorf("expected attr: %s", out)
	}
}

func TestOutput_ManyAttributes(t *testing.T) {
	base, buf := testLogger(t)
	log := base.WithAttribute("g1", "a").WithAttribute("g2", "b").WithAttribute("g3", "c")
	log.Info().Attr("l1", 1).Attr("l2", 2).Attr("l3", 3).Msg("test")
	out := buf.String()
	for _, key := range []string{"g1", "g2", "g3", "l1", "l2", "l3"} {
		if !strings.Contains(out, key) {
			t.Errorf("expected key %q: %s", key, out)
		}
	}
}

func TestOutput_AttributeTypes(t *testing.T) {
	log, buf := testLogger(t)
	log.Info().
		Attr("str", "hello").
		Attr("int", 42).
		Attr("float", 3.14).
		Attr("bool", true).
		Msg("types")
	out := buf.String()
	if !strings.Contains(out, "str(hello)") {
		t.Errorf("expected str: %s", out)
	}
	if !strings.Contains(out, "int(42)") {
		t.Errorf("expected int: %s", out)
	}
	if !strings.Contains(out, "bool(true)") {
		t.Errorf("expected bool: %s", out)
	}
}

// ---------------------------------------------------------------------------
// output: message / error / stack combinations
// ---------------------------------------------------------------------------

func TestOutput_MessageOnly(t *testing.T) {
	log, buf := testLogger(t)
	log.Info().Msg("hello")
	out := buf.String()
	if !strings.Contains(out, " -> hello") {
		t.Errorf("expected message: %s", out)
	}
}

func TestOutput_ErrorOnly(t *testing.T) {
	log, buf := testLogger(t)
	log.Error().MsgErr(io.EOF)
	out := buf.String()
	if !strings.Contains(out, io.EOF.Error()) {
		t.Errorf("expected error: %s", out)
	}
}

func TestOutput_MessageAndError(t *testing.T) {
	log, buf := testLogger(t)
	log.Error().Cause(io.EOF).Msg("failed")
	out := buf.String()
	if !strings.Contains(out, "failed: EOF") {
		t.Errorf("expected 'failed: EOF': %s", out)
	}
}

func TestOutput_MessageAndStack(t *testing.T) {
	log, buf := testLogger(t)
	log.Info().Stack().Msg("with trace")
	out := buf.String()
	lines := strings.Split(out, "\n")
	if len(lines) < 3 {
		t.Errorf("expected stack lines, got: %s", out)
	}
}

func TestOutput_AllFields(t *testing.T) {
	log, buf := testLogger(t)
	log.Error().Stack().Cause(io.EOF).Attr("k", "v").Msg("all")
	out := buf.String()
	if !strings.Contains(out, "all: EOF") {
		t.Errorf("expected 'all: EOF': %s", out)
	}
	if !strings.Contains(out, "k(v)") {
		t.Errorf("expected attr: %s", out)
	}
	lines := strings.Split(out, "\n")
	if len(lines) < 3 {
		t.Errorf("expected stack lines, got: %s", out)
	}
}

// ---------------------------------------------------------------------------
// module depth
// ---------------------------------------------------------------------------

func TestOutput_SingleModule(t *testing.T) {
	log, buf := testLogger(t)
	log.Info().Msg("x")
	if !strings.Contains(buf.String(), "test ->") {
		t.Errorf("expected single module: %s", buf.String())
	}
}

func TestOutput_DeepModules(t *testing.T) {
	log, buf := testLogger(t)
	db := log.Module("db", "queries")
	cache := db.Module("cache", "redis")
	cache.Info().Msg("deep")
	out := buf.String()
	for _, m := range []string{"test", "db", "cache"} {
		if !strings.Contains(out, m) {
			t.Errorf("expected module %q: %s", m, out)
		}
	}
	for _, s := range []string{"queries", "redis"} {
		if !strings.Contains(out, s) {
			t.Errorf("expected scope %q: %s", s, out)
		}
	}
}

func TestOutput_Modules_NoScope(t *testing.T) {
	log, buf := testLogger(t)
	db := log.Module("db")
	db.Info().Msg("test")
	out := buf.String()
	if !strings.Contains(out, "test db") {
		t.Errorf("expected module path, got: %s", out)
	}
}

// ---------------------------------------------------------------------------
// colors
// ---------------------------------------------------------------------------

func TestOutput_ColorsEnabled(t *testing.T) {
	log, buf := testLogger(t)
	log.Info().Msg("hello")
	out := buf.String()
	if !strings.Contains(out, "\u001B[36m") {
		t.Errorf("expected cyan for INFO: %q", out)
	}
	if !strings.Contains(out, resetCode) {
		t.Errorf("expected reset: %q", out)
	}
}

func TestOutput_DisableColors_PerHandler(t *testing.T) {
	log, buf := testLogger(t, Config{DisableColors: true})
	log.Info().Msg("hello")
	out := buf.String()
	if strings.Contains(out, "\u001B[") {
		t.Errorf("expected no ANSI codes: %q", out)
	}
}

func TestOutput_DisableColors_Global(t *testing.T) {
	old := DisableColors
	DisableColors = true
	defer func() { DisableColors = old }()

	log, buf := testLogger(t)
	log.Info().Msg("hello")
	out := buf.String()
	if strings.Contains(out, "\u001B[") {
		t.Errorf("expected no ANSI codes with global: %q", out)
	}
}

func TestOutput_Colors_GlobalOverridesHandler(t *testing.T) {
	old := DisableColors
	DisableColors = true
	defer func() { DisableColors = old }()

	log, buf := testLogger(t, Config{DisableColors: false})
	log.Info().Msg("x")
	out := buf.String()
	if strings.Contains(out, "\u001B[") {
		t.Error("DisableColors=true should override per-handler false")
	}
}

func TestOutput_LevelColors(t *testing.T) {
	log, buf := testLogger(t)
	log.Error().Msg("error")
	if !strings.Contains(buf.String(), "\u001B[1;31m") {
		t.Errorf("expected bold red for ERROR: %q", buf.String())
	}

	buf.Reset()
	log.Warn().Msg("warn")
	if !strings.Contains(buf.String(), "\u001B[33m") {
		t.Errorf("expected yellow for WARNING: %q", buf.String())
	}

	buf.Reset()
	log.WithLevel(gcore.LevelTrace).WithAutoStack(false).Debug().Msg("debug")
	if !strings.Contains(buf.String(), "\u001B[35m") {
		t.Errorf("expected purple for DEBUG: %q", buf.String())
	}

	buf.Reset()
	log.WithLevel(gcore.LevelTrace).Trace().Msg("trace")
	if !strings.Contains(buf.String(), "\u001B[3;39m") {
		t.Errorf("expected italic for TRACE: %q", buf.String())
	}
}

// ---------------------------------------------------------------------------
// severity filtering
// ---------------------------------------------------------------------------

func TestOutput_SeverityFiltering(t *testing.T) {
	log, buf := testLogger(t, Config{Base: gcore.Config{Severity: gcore.LevelWarning}})
	log.Info().Msg("no")
	if buf.Len() > 0 {
		t.Error("Info filtered")
	}
	buf.Reset()
	log.Warn().Msg("yes")
	if buf.Len() == 0 {
		t.Error("Warn should pass")
	}
}

// ---------------------------------------------------------------------------
// custom writer
// ---------------------------------------------------------------------------

func TestOutput_CustomWriter(t *testing.T) {
	buf := &bytes.Buffer{}
	cfg := Config{Base: gcore.Config{StandardOutput: buf}}
	log := gcore.Init("test", Init(cfg))
	log.Info().Msg("custom")
	if buf.Len() == 0 {
		t.Error("expected output in custom writer")
	}
}

// ---------------------------------------------------------------------------
// appendAttribute
// ---------------------------------------------------------------------------

func TestAppendAttribute_String(t *testing.T) {
	buf := make([]byte, 0, 64)
	buf = appendAttribute(buf, "hello")
	if string(buf) != "hello" {
		t.Errorf("expected 'hello', got %q", buf)
	}
}

func TestAppendAttribute_Bytes(t *testing.T) {
	buf := make([]byte, 0, 64)
	buf = appendAttribute(buf, []byte("world"))
	if string(buf) != "world" {
		t.Errorf("expected 'world', got %q", buf)
	}
}

func TestAppendAttribute_Int(t *testing.T) {
	buf := make([]byte, 0, 64)
	buf = appendAttribute(buf, 123)
	if !strings.Contains(string(buf), "123") {
		t.Errorf("expected '123', got %q", buf)
	}
}

func TestAppendAttribute_Bool(t *testing.T) {
	buf := make([]byte, 0, 64)
	buf = appendAttribute(buf, true)
	if !strings.Contains(string(buf), "true") {
		t.Errorf("expected 'true', got %q", buf)
	}
}

func TestAppendAttribute_Struct(t *testing.T) {
	buf := make([]byte, 0, 256)
	buf = appendAttribute(buf, struct{ X int }{42})
	if !strings.Contains(string(buf), `"X":42`) {
		t.Errorf("expected marshalled struct, got %q", buf)
	}
}

// ---------------------------------------------------------------------------
// init (GOLOG_DISABLE_COLORS)
// ---------------------------------------------------------------------------

func TestInit_DisableColorsEnv(t *testing.T) {
	old := DisableColors
	defer func() { DisableColors = old }()

	t.Setenv("GOLOG_DISABLE_COLORS", "1")
	DisableColors = true
	if !DisableColors {
		t.Error("DisableColors should be true when env is set")
	}
}

// ===========================================================================
// Benchmarks
// ===========================================================================

func BenchmarkInit(b *testing.B) {
	for range b.N {
		_ = Init()
	}
}

// ------- message length (colors off + on) -------

var benchMsgLengths = []struct {
	name string
	msg  string
}{
	{"1B", "x"},
	{"16B", "hello golog test"},
	{"64B", strings.Repeat("abcdefgh", 8)},
	{"256B", strings.Repeat("abcdefghijklmnop", 16)},
	{"1KB", strings.Repeat("abcdefghij", 100)},
}

func BenchmarkInfo_Msg(b *testing.B) {
	for _, tc := range benchMsgLengths {
		b.Run(tc.name, func(b *testing.B) {
			log := benchLogger(b, Config{DisableColors: true})
			b.ResetTimer()
			for range b.N {
				log.Info().Msg(tc.msg)
			}
		})
	}
}

func BenchmarkInfo_Msg_ColorsOn(b *testing.B) {
	for _, tc := range benchMsgLengths {
		b.Run(tc.name, func(b *testing.B) {
			log := benchLogger(b, Config{DisableColors: false})
			b.ResetTimer()
			for range b.N {
				log.Info().Msg(tc.msg)
			}
		})
	}
}

// ------- formatted -------

func BenchmarkInfo_Msgf(b *testing.B) {
	log := benchLogger(b, Config{DisableColors: true})
	b.ResetTimer()
	for range b.N {
		log.Info().Msgf("hello %s %d", "world", 42)
	}
}

func BenchmarkInfo_Msgf_ManyArgs(b *testing.B) {
	log := benchLogger(b, Config{DisableColors: true})
	b.ResetTimer()
	for range b.N {
		log.Info().Msgf("a=%s b=%d c=%v d=%s e=%d", "x", 1, true, "y", 2)
	}
}

// ------- error -------

func BenchmarkError_MsgErr(b *testing.B) {
	log := benchLogger(b, Config{DisableColors: true})
	err := io.EOF
	b.ResetTimer()
	for range b.N {
		log.Error().MsgErr(err)
	}
}

func BenchmarkError_MessageAndError(b *testing.B) {
	log := benchLogger(b, Config{DisableColors: true})
	err := io.EOF
	b.ResetTimer()
	for range b.N {
		log.Error().Cause(err).Msg("something went wrong")
	}
}

// ------- attributes -------

var benchAttrCounts = []int{0, 1, 3, 5, 10}

func BenchmarkInfo_Attrs(b *testing.B) {
	for _, n := range benchAttrCounts {
		b.Run(fmt.Sprintf("%d", n), func(b *testing.B) {
			log := benchLogger(b, Config{DisableColors: true})
			b.ResetTimer()
			for range b.N {
				m := log.Info()
				for i := range n {
					m = m.Attr("k", i)
				}
				m.Msg("hello")
			}
		})
	}
}

func BenchmarkInfo_Attrs_ColorsOn(b *testing.B) {
	for _, n := range benchAttrCounts {
		b.Run(fmt.Sprintf("%d", n), func(b *testing.B) {
			log := benchLogger(b, Config{DisableColors: false})
			b.ResetTimer()
			for range b.N {
				m := log.Info()
				for i := range n {
					m = m.Attr("k", i)
				}
				m.Msg("hello")
			}
		})
	}
}

// ------- stack -------

func BenchmarkError_Stack(b *testing.B) {
	log := benchLogger(b, Config{DisableColors: true})
	b.ResetTimer()
	for range b.N {
		log.Error().Stack().Msg("boom")
	}
}

func BenchmarkError_StackMsgErr(b *testing.B) {
	log := benchLogger(b, Config{DisableColors: true})
	err := io.EOF
	b.ResetTimer()
	for range b.N {
		log.Error().Stack().MsgErr(err)
	}
}

// ------- combined -------

func BenchmarkInfo_Combined(b *testing.B) {
	log := benchLogger(b, Config{DisableColors: true})
	b.ResetTimer()
	for range b.N {
		log.Info().Attr("reqID", "abc123").Attr("user", "admin").Msg("request processed")
	}
}
