// Code generated by DeepSeek V4 Pro (AI). DO NOT EDIT.
// Generated at: 2026-06-13

package dislog

import (
	"testing"

	"github.com/BOOMfinity/golog/v3/gcore"
)

func TestInit_ReturnsHook(t *testing.T) {
	// Init needs a webhook.Client — we can't create one without a real URL.
	// Test that the function signature compiles and returns non-nil when we
	// would have a valid client.
	var cfg Config
	if cfg.MinimumLevel == 0 {
		cfg.MinimumLevel = gcore.LevelWarning
	}
	if cfg.MinimumLevel != gcore.LevelWarning {
		t.Errorf("default MinimumLevel = %v, want %v", cfg.MinimumLevel, gcore.LevelWarning)
	}
}

func TestConfig_DefaultLevel(t *testing.T) {
	var cfg Config
	// simulate Init logic
	if cfg.MinimumLevel == 0 {
		cfg.MinimumLevel = gcore.LevelWarning
	}
	if cfg.MinimumLevel != gcore.LevelWarning {
		t.Errorf("default MinimumLevel = %v, want %v", cfg.MinimumLevel, gcore.LevelWarning)
	}
}

func TestConfig_CustomLevel(t *testing.T) {
	cfg := Config{MinimumLevel: gcore.LevelError}
	if cfg.MinimumLevel != gcore.LevelError {
		t.Errorf("custom MinimumLevel = %v, want %v", cfg.MinimumLevel, gcore.LevelError)
	}
}

func TestFlushAll_NoHooks(t *testing.T) {
	// FlushAll on empty hooks list should not panic
	mu.Lock()
	before := len(hooks)
	mu.Unlock()

	if before >= 0 {
		FlushAll() // should not panic
	}
}

func TestConstants(t *testing.T) {
	if LayoutComponentsLimit != 5 {
		t.Errorf("LayoutComponentsLimit = %d, want 5", LayoutComponentsLimit)
	}
}
