// Code generated by DeepSeek V4 Pro (AI). DO NOT EDIT.
// Generated at: 2026-06-13

package jsonfmt

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"strings"
	"testing"
	"time"

	"github.com/BOOMfinity/golog/v3/gcore"
)

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

func testLogger(t *testing.T, cfg ...Config) (*gcore.Logger, *bytes.Buffer) {
	t.Helper()
	buf := &bytes.Buffer{}
	cfg2 := Config{}
	if len(cfg) > 0 {
		cfg2 = cfg[0]
	}
	cfg2.Base.StandardOutput = buf
	log := gcore.Init("test", Init(cfg2))
	return log, buf
}

func benchLogger(b *testing.B, cfg Config) *gcore.Logger {
	b.Helper()
	cfg.Base.StandardOutput = io.Discard
	return gcore.Init("test", Init(cfg))
}

// ---------------------------------------------------------------------------
// Init
// ---------------------------------------------------------------------------

func TestInit_ReturnsFormatter(t *testing.T) {
	f := Init()
	if f == nil {
		t.Fatal("Init returned nil")
	}
}

func TestInit_DefaultTimeFormat(t *testing.T) {
	log, buf := testLogger(t)
	log.Info().Msg("hello")
	if !strings.Contains(buf.String(), time.Now().Format("2006-01-02")) {
		t.Errorf("expected RFC3339 date in output: %s", buf.String())
	}
}

func TestInit_CustomTimeFormat(t *testing.T) {
	log, buf := testLogger(t, Config{Base: gcore.Config{TimeFormat: time.RFC822}})
	log.Info().Msg("hello")
	out := buf.String()
	var obj map[string]any
	if err := json.Unmarshal([]byte(out), &obj); err != nil {
		t.Fatalf("invalid JSON: %v\n%s", err, out)
	}
	if _, err := time.Parse(time.RFC822, obj["time"].(string)); err != nil {
		t.Errorf("time not in RFC822: %s", obj["time"])
	}
}

// ---------------------------------------------------------------------------
// output: message lengths
// ---------------------------------------------------------------------------

func TestOutput_ShortMessage(t *testing.T) {
	log, buf := testLogger(t)
	log.Info().Msg("x")
	if !strings.Contains(buf.String(), `"message":"x"`) {
		t.Errorf("expected short message: %s", buf.String())
	}
}

func TestOutput_LongMessage(t *testing.T) {
	msg := strings.Repeat("abcdefghij", 200) // 2 KB
	log, buf := testLogger(t)
	log.Info().Msg(msg)
	if !strings.Contains(buf.String(), msg) {
		t.Error("expected long message in output")
	}
}

func TestOutput_UnicodeMessage(t *testing.T) {
	log, buf := testLogger(t)
	log.Info().Msg("żółć 日本語 🚀")
	out := buf.String()
	for _, s := range []string{"żółć", "日本語", "🚀"} {
		if !strings.Contains(out, s) {
			t.Errorf("expected unicode %q in output: %s", s, out)
		}
	}
}

// ---------------------------------------------------------------------------
// output: attributes
// ---------------------------------------------------------------------------

func TestOutput_NoAttributes(t *testing.T) {
	log, buf := testLogger(t)
	log.Info().Msg("plain")
	out := buf.String()
	var obj map[string]any
	json.Unmarshal([]byte(out), &obj)
	if _, ok := obj["global"]; ok {
		t.Error("should not have global attr")
	}
}

func TestOutput_SingleAttribute(t *testing.T) {
	log, buf := testLogger(t)
	log.Info().Attr("key", "val").Msg("test")
	out := buf.String()
	if !strings.Contains(out, `"key":"val"`) {
		t.Errorf("expected attr: %s", out)
	}
}

func TestOutput_ManyAttributes(t *testing.T) {
	base, buf := testLogger(t)
	log := base.WithAttribute("g1", "a").WithAttribute("g2", "b").WithAttribute("g3", "c")
	log.Info().Attr("l1", 1).Attr("l2", 2).Attr("l3", 3).Msg("test")
	out := buf.String()
	for _, key := range []string{"g1", "g2", "g3", "l1", "l2", "l3"} {
		if !strings.Contains(out, `"`+key+`"`) {
			t.Errorf("expected key %q: %s", key, out)
		}
	}
}

func TestOutput_AttributeTypes(t *testing.T) {
	log, buf := testLogger(t)
	log.Info().
		Attr("str", "hello").
		Attr("int", 42).
		Attr("float", 3.14).
		Attr("bool", true).
		Attr("nil", nil).
		Msg("types")

	out := buf.String()
	var obj map[string]any
	if err := json.Unmarshal([]byte(out), &obj); err != nil {
		t.Fatalf("invalid JSON: %v", err)
	}
	if obj["str"] != "hello" {
		t.Errorf("str = %v", obj["str"])
	}
	if obj["int"] != float64(42) {
		t.Errorf("int = %v", obj["int"])
	}
	if obj["bool"] != true {
		t.Errorf("bool = %v", obj["bool"])
	}
	if obj["nil"] != nil {
		t.Errorf("nil = %v", obj["nil"])
	}
}

// ---------------------------------------------------------------------------
// output: message / error / stack combinations
// ---------------------------------------------------------------------------

func TestOutput_MessageAndError(t *testing.T) {
	log, buf := testLogger(t)
	log.Error().Cause(io.EOF).Msg("failed")
	out := buf.String()
	if !strings.Contains(out, `"message":"failed"`) {
		t.Errorf("expected message: %s", out)
	}
	if !strings.Contains(out, `"error":"EOF"`) {
		t.Errorf("expected error: %s", out)
	}
}

func TestOutput_MessageAndStack(t *testing.T) {
	log, buf := testLogger(t)
	log.Info().Stack().Msg("with trace")
	out := buf.String()
	if !strings.Contains(out, `"message"`) && !strings.Contains(out, `"stack"`) {
		t.Error("expected message and stack")
	}
}

func TestOutput_AllFields(t *testing.T) {
	log, buf := testLogger(t)
	log.Error().Stack().Cause(io.EOF).Attr("k", "v").Msg("all")
	out := buf.String()
	var obj map[string]any
	if err := json.Unmarshal([]byte(out), &obj); err != nil {
		t.Fatalf("invalid JSON: %v\n%s", err, out)
	}
	for _, f := range []string{"time", "level", "module", "message", "error", "stack", "k"} {
		if _, ok := obj[f]; !ok {
			t.Errorf("missing field %q", f)
		}
	}
}

func TestOutput_ErrorOnly(t *testing.T) {
	log, buf := testLogger(t)
	log.Error().MsgErr(io.EOF)
	out := buf.String()
	if strings.Contains(out, `"message"`) {
		t.Error("should not have message field")
	}
	if !strings.Contains(out, io.EOF.Error()) {
		t.Error("expected error")
	}
}

func TestOutput_MsgErrVsMsgErr(t *testing.T) {
	// MsgErr with error -> no message field
	log, buf := testLogger(t)
	log.Error().MsgErr(io.EOF)
	if strings.Contains(buf.String(), `"message"`) {
		t.Error("MsgErr should not emit message field")
	}
}

// ---------------------------------------------------------------------------
// escaping combinations
// ---------------------------------------------------------------------------

func TestOutput_Escaped_Both(t *testing.T) {
	log, buf := testLogger(t)
	log.Info().Attr("key", `"quoted"`).Msg(`"hi"`)
	out := buf.String()
	if strings.Contains(out, `"key":""quoted""`) {
		t.Error("attr should be escaped by default")
	}
	if strings.Contains(out, `"message":""hi""`) {
		t.Error("message should be escaped by default")
	}
}

func TestOutput_Disabled_Both(t *testing.T) {
	log, buf := testLogger(t, Config{
		DisableMessageEscaping:   true,
		DisableAttributeEscaping: true,
	})
	log.Info().Attr("key", `"raw"`).Msg(`"hi"`)
	out := buf.String()
	if !strings.Contains(out, `"key":""raw""`) {
		t.Errorf("attr should be raw: %s", out)
	}
	if !strings.Contains(out, `"message":""hi""`) {
		t.Errorf("message should be raw: %s", out)
	}
}

func TestOutput_DisabledAttrOnly(t *testing.T) {
	log, buf := testLogger(t, Config{DisableAttributeEscaping: true})
	log.Info().Attr("key", `"raw"`).Msg(`"hi"`)
	out := buf.String()
	if !strings.Contains(out, `"key":""raw""`) {
		t.Errorf("attr should be raw: %s", out)
	}
	if strings.Contains(out, `"message":""hi""`) {
		t.Error("message should be escaped")
	}
}

func TestOutput_DisabledMsgOnly(t *testing.T) {
	log, buf := testLogger(t, Config{DisableMessageEscaping: true})
	log.Info().Attr("key", `"raw"`).Msg(`"hi"`)
	out := buf.String()
	if strings.Contains(out, `"key":""raw""`) {
		t.Error("attr should be escaped")
	}
	if !strings.Contains(out, `"message":""hi""`) {
		t.Errorf("message should be raw: %s", out)
	}
}

// ---------------------------------------------------------------------------
// module depth
// ---------------------------------------------------------------------------

func TestOutput_SingleModule(t *testing.T) {
	log, buf := testLogger(t)
	log.Info().Msg("x")
	if !strings.Contains(buf.String(), `"module":"test"`) {
		t.Errorf("expected 'test' module: %s", buf.String())
	}
}

func TestOutput_DeepModules(t *testing.T) {
	log, buf := testLogger(t)
	db := log.Module("db", "queries")
	cache := db.Module("cache", "redis")
	cache.Info().Msg("deep")
	out := buf.String()
	for _, m := range []string{"test", "db", "cache"} {
		if !strings.Contains(out, m) {
			t.Errorf("expected module %q: %s", m, out)
		}
	}
	for _, s := range []string{"queries", "redis"} {
		if !strings.Contains(out, s) {
			t.Errorf("expected scope %q: %s", s, out)
		}
	}
}

// ---------------------------------------------------------------------------
// severity filtering
// ---------------------------------------------------------------------------

func TestOutput_SeverityFiltering(t *testing.T) {
	log, buf := testLogger(t, Config{Base: gcore.Config{Severity: gcore.LevelWarning}})
	log.Info().Msg("no")
	if buf.Len() > 0 {
		t.Error("Info filtered")
	}
	buf.Reset()
	log.Warn().Msg("yes")
	if buf.Len() == 0 {
		t.Error("Warn should pass")
	}
}

// ---------------------------------------------------------------------------
// custom writer
// ---------------------------------------------------------------------------

func TestOutput_CustomWriter(t *testing.T) {
	buf := &bytes.Buffer{}
	cfg := Config{Base: gcore.Config{StandardOutput: buf}}
	log := gcore.Init("test", Init(cfg))
	log.Info().Msg("custom")
	if buf.Len() == 0 {
		t.Error("expected output in custom writer")
	}
}

// ---------------------------------------------------------------------------
// complex attribute types
// ---------------------------------------------------------------------------

func TestOutput_ComplexAttribute(t *testing.T) {
	log, buf := testLogger(t, Config{DisableAttributeEscaping: true})
	log.Info().Attr("data", struct{ X int }{42}).Msg("test")
	out := buf.String()
	if !strings.Contains(out, `"X":42`) {
		t.Errorf("expected marshalled struct: %s", out)
	}
}

func TestOutput_SliceAttribute(t *testing.T) {
	log, buf := testLogger(t, Config{DisableAttributeEscaping: true})
	log.Info().Attr("items", []int{1, 2, 3}).Msg("test")
	out := buf.String()
	if !strings.Contains(out, "[1,2,3]") {
		t.Errorf("expected array: %s", out)
	}
}

func TestOutput_BytesAttribute(t *testing.T) {
	log, buf := testLogger(t, Config{DisableAttributeEscaping: true})
	log.Info().Attr("raw", []byte("bytes")).Msg("test")
	out := buf.String()
	if !strings.Contains(out, `"raw":bytes`) {
		t.Errorf("expected raw bytes: %s", out)
	}
}

// ===========================================================================
// Benchmarks
// ===========================================================================

func BenchmarkInit(b *testing.B) {
	for range b.N {
		_ = Init()
	}
}

// ------- message length (escaped + raw) -------

var benchMsgLengths = []struct {
	name string
	msg  string
}{
	{"1B", "x"},
	{"16B", "hello golog test"},
	{"64B", strings.Repeat("abcdefgh", 8)},
	{"256B", strings.Repeat("abcdefghijklmnop", 16)},
	{"1KB", strings.Repeat("abcdefghij", 100)},
}

func BenchmarkInfo_Msg(b *testing.B) {
	for _, tc := range benchMsgLengths {
		b.Run(tc.name, func(b *testing.B) {
			log := benchLogger(b, Config{})
			b.ResetTimer()
			for range b.N {
				log.Info().Msg(tc.msg)
			}
		})
	}
}

func BenchmarkInfo_Msg_Raw(b *testing.B) {
	for _, tc := range benchMsgLengths {
		b.Run(tc.name, func(b *testing.B) {
			log := benchLogger(b, Config{DisableMessageEscaping: true})
			b.ResetTimer()
			for range b.N {
				log.Info().Msg(tc.msg)
			}
		})
	}
}

// ------- formatted -------

func BenchmarkInfo_Msgf(b *testing.B) {
	log := benchLogger(b, Config{})
	b.ResetTimer()
	for range b.N {
		log.Info().Msgf("hello %s %d", "world", 42)
	}
}

func BenchmarkInfo_Msgf_ManyArgs(b *testing.B) {
	log := benchLogger(b, Config{})
	b.ResetTimer()
	for range b.N {
		log.Info().Msgf("a=%s b=%d c=%v d=%s e=%d", "x", 1, true, "y", 2)
	}
}

// ------- error -------

func BenchmarkError_MsgErr(b *testing.B) {
	log := benchLogger(b, Config{})
	err := io.EOF
	b.ResetTimer()
	for range b.N {
		log.Error().MsgErr(err)
	}
}

func BenchmarkError_MessageAndError(b *testing.B) {
	log := benchLogger(b, Config{})
	err := io.EOF
	b.ResetTimer()
	for range b.N {
		log.Error().Cause(err).Msg("something went wrong")
	}
}

// ------- attributes -------

var benchAttrCounts = []int{0, 1, 3, 5, 10}

func BenchmarkInfo_Attrs(b *testing.B) {
	for _, n := range benchAttrCounts {
		b.Run(fmt.Sprintf("%d", n), func(b *testing.B) {
			log := benchLogger(b, Config{})
			b.ResetTimer()
			for range b.N {
				m := log.Info()
				for i := range n {
					m = m.Attr("k", i)
				}
				m.Msg("hello")
			}
		})
	}
}

func BenchmarkInfo_Attrs_Raw(b *testing.B) {
	for _, n := range benchAttrCounts {
		b.Run(fmt.Sprintf("%d", n), func(b *testing.B) {
			log := benchLogger(b, Config{DisableAttributeEscaping: true})
			b.ResetTimer()
			for range b.N {
				m := log.Info()
				for i := range n {
					m = m.Attr("k", i)
				}
				m.Msg("hello")
			}
		})
	}
}

// ------- stack -------

func BenchmarkError_Stack(b *testing.B) {
	log := benchLogger(b, Config{})
	b.ResetTimer()
	for range b.N {
		log.Error().Stack().Msg("boom")
	}
}

func BenchmarkError_StackMsgErr(b *testing.B) {
	log := benchLogger(b, Config{})
	err := io.EOF
	b.ResetTimer()
	for range b.N {
		log.Error().Stack().MsgErr(err)
	}
}

// ------- combined -------

func BenchmarkInfo_Combined(b *testing.B) {
	log := benchLogger(b, Config{})
	b.ResetTimer()
	for range b.N {
		log.Info().Attr("reqID", "abc123").Attr("user", "admin").Msg("request processed")
	}
}
