// Code generated by DeepSeek V4 Pro (AI). DO NOT EDIT.
// Generated at: 2026-06-13

package sentrylog

import (
	"context"
	"io"
	"testing"

	"github.com/BOOMfinity/golog/v3/gcore"
)

// stubContext implements gcore.Context with minimal data.
type stubContext struct {
	err  error
	msg  string
	lvl  gcore.Level
	code int
}

func (s *stubContext) Modules() ([]string, []string)                      { return []string{"test"}, []string{""} }
func (s *stubContext) Level() gcore.Level                                 { return s.lvl }
func (s *stubContext) Attributes() ([]gcore.Attribute, []gcore.Attribute) { return nil, nil }
func (s *stubContext) Message() string                                    { return s.msg }
func (s *stubContext) HasMessage() bool                                   { return s.msg != "" }
func (s *stubContext) StackTrace() string                                 { return "" }
func (s *stubContext) HasStackTrace() bool                                { return false }
func (s *stubContext) Error() error                                       { return s.err }
func (s *stubContext) HasError() bool                                     { return s.err != nil }
func (s *stubContext) Context() context.Context                           { return context.Background() }
func (s *stubContext) ExitCode() int                                      { return s.code }
func (s *stubContext) HasExitCode() bool                                  { return s.code != 0 }

func TestInit_ReturnsHook(t *testing.T) {
	h := Init(true, false)
	if h == nil {
		t.Fatal("Init returned nil")
	}
}

func TestInit_BothFalse(t *testing.T) {
	h := Init(false, false)
	if h == nil {
		t.Fatal("Init returned nil")
	}
	// both disabled — hook should not panic
	h(&stubContext{msg: "hello", lvl: gcore.LevelInfo})
}

func TestHook_ExceptionsTrue(t *testing.T) {
	h := Init(true, false)
	// should not panic even without sentry hub init
	h(&stubContext{err: io.EOF, lvl: gcore.LevelError})
}

func TestHook_LogsTrue(t *testing.T) {
	h := Init(false, true)
	// should not panic — sentry.NewLogger handles missing hub gracefully
	h(&stubContext{msg: "test", lvl: gcore.LevelInfo})
}

func TestHook_NoError_SkipsException(t *testing.T) {
	h := Init(true, false)
	// HasError() == false, so CaptureException is skipped
	h(&stubContext{msg: "all good", lvl: gcore.LevelInfo})
}
