// Code generated by DeepSeek V4 Pro (AI). DO NOT EDIT.
// Generated at: 2026-06-13

package gcore

import (
	"bytes"
	"context"
	"io"
	"os"
	"strings"
	"sync"
	"testing"
)

// ---------------------------------------------------------------------------
// helpers
// ---------------------------------------------------------------------------

func testFormatter(t *testing.T, buf *bytes.Buffer) Formatter {
	t.Helper()
	return func(entry Context) {
		modules, scopes := entry.Modules()
		buf.WriteString(strings.Join(modules, "."))
		if len(scopes) > 0 {
			last := scopes[len(scopes)-1]
			if last != "" {
				buf.WriteString("@")
				buf.WriteString(last)
			}
		}
		buf.WriteString(" | ")
		buf.WriteString(entry.Level().String())
		buf.WriteString(" | ")
		buf.WriteString(entry.Message())
		if entry.HasError() {
			buf.WriteString(": ")
			buf.WriteString(entry.Error().Error())
		}
		global, local := entry.Attributes()
		for _, a := range global {
			buf.WriteString(" | ")
			buf.WriteString(a.Name)
		}
		for _, a := range local {
			buf.WriteString(" | ")
			buf.WriteString(a.Name)
		}
		if entry.HasStackTrace() {
			buf.WriteString(" | stack")
		}
		buf.WriteByte('\n')
	}
}

// ---------------------------------------------------------------------------
// Level
// ---------------------------------------------------------------------------

func TestLevel_String(t *testing.T) {
	tests := []struct {
		level Level
		want  string
	}{
		{LevelFatal, "FATAL"},
		{LevelError, "ERROR"},
		{LevelWarning, "WARNING"},
		{LevelInfo, "INFO"},
		{LevelDebug, "DEBUG"},
		{LevelTrace, "TRACE"},
	}
	for _, tt := range tests {
		if got := tt.level.String(); got != tt.want {
			t.Errorf("%d.String() = %q, want %q", tt.level, got, tt.want)
		}
	}
}

func TestLevel_PanicOnInvalid(t *testing.T) {
	defer func() {
		if r := recover(); r == nil {
			t.Error("expected panic for invalid level")
		}
	}()
	_ = Level(99).String()
}

// ---------------------------------------------------------------------------
// Logger.Init
// ---------------------------------------------------------------------------

func TestInit(t *testing.T) {
	var buf bytes.Buffer
	log := Init("test", testFormatter(t, &buf))
	if log == nil {
		t.Fatal("Init returned nil")
	}
	if log.level != LevelInfo {
		t.Errorf("default level = %v, want %v", log.level, LevelInfo)
	}
	if !log.stackOnError {
		t.Error("stackOnError should default to true")
	}
}

func TestInit_NilFormatterPanics(t *testing.T) {
	defer func() {
		if r := recover(); r == nil {
			t.Error("expected panic for nil formatter")
		}
	}()
	Init("test", nil)
}

func TestInit_EmptyNameDefaultsToApp(t *testing.T) {
	var buf bytes.Buffer
	log := Init("", testFormatter(t, &buf))
	log.Info().Msg("hello")
	if !strings.Contains(buf.String(), "app") {
		t.Errorf("expected default name 'app', got output: %s", buf.String())
	}
}

// ---------------------------------------------------------------------------
// Logger.Clone
// ---------------------------------------------------------------------------

func TestLogger_Clone(t *testing.T) {
	var buf bytes.Buffer
	original := Init("app", testFormatter(t, &buf))
	original.WithAttribute("key", "val")

	clone := original.Clone()
	if clone == original {
		t.Error("Clone should return a different instance")
	}
	if clone.level != original.level {
		t.Error("Clone should copy level")
	}
	if clone.stackOnError != original.stackOnError {
		t.Error("Clone should copy stackOnError")
	}
	if len(clone.modules) != len(original.modules) {
		t.Error("Clone should copy modules")
	}
	if len(clone.attrs) != len(original.attrs) {
		t.Error("Clone should copy attributes")
	}
}

func TestLogger_Clone_WithScope(t *testing.T) {
	var buf bytes.Buffer
	original := Init("app", testFormatter(t, &buf))
	app := original.Module("db", "queries")
	clone := app.Clone("noqueries")
	if clone.scopes[len(clone.scopes)-1] != "noqueries" {
		t.Errorf("Clone scope = %q, want %q", clone.scopes[len(clone.scopes)-1], "noqueries")
	}
	if clone.modules[len(clone.modules)-1] != "db" {
		t.Errorf("Clone module = %q, want %q", clone.modules[len(clone.modules)-1], "db")
	}
}

// ---------------------------------------------------------------------------
// Logger.Module
// ---------------------------------------------------------------------------

func TestLogger_Module(t *testing.T) {
	var buf bytes.Buffer
	root := Init("app", testFormatter(t, &buf))
	db := root.Module("db", "queries")

	if len(db.modules) != 2 {
		t.Fatalf("modules len = %d, want 2", len(db.modules))
	}
	if db.modules[1] != "db" {
		t.Errorf("module[1] = %q, want %q", db.modules[1], "db")
	}
	if db.scopes[1] != "queries" {
		t.Errorf("scope[1] = %q, want %q", db.scopes[1], "queries")
	}
}

func TestLogger_Module_EmptyNamePanics(t *testing.T) {
	var buf bytes.Buffer
	root := Init("app", testFormatter(t, &buf))
	defer func() {
		if r := recover(); r == nil {
			t.Error("expected panic for empty module name")
		}
	}()
	root.Module("")
}

func TestLogger_Module_WithoutScope(t *testing.T) {
	var buf bytes.Buffer
	root := Init("app", testFormatter(t, &buf))
	db := root.Module("db")

	if db.scopes[1] != "" {
		t.Errorf("scope without name = %q, want empty", db.scopes[1])
	}
}

// ---------------------------------------------------------------------------
// Logger.Scoped
// ---------------------------------------------------------------------------

func TestLogger_Scoped(t *testing.T) {
	var buf bytes.Buffer
	root := Init("app", testFormatter(t, &buf)).WithAttribute("global", true)

	root.Scoped("transaction", func(log *Logger) {
		log.Info().Attr("local", true).Msg("inside scope")
	})

	out := buf.String()
	if !strings.Contains(out, "@transaction") {
		t.Errorf("expected '@transaction' in output, got: %s", out)
	}
	if !strings.Contains(out, "inside scope") {
		t.Errorf("expected 'inside scope' in output, got: %s", out)
	}
	if !strings.Contains(out, "global") {
		t.Errorf("expected global attribute in output, got: %s", out)
	}
	if !strings.Contains(out, "local") {
		t.Errorf("expected local attribute in output, got: %s", out)
	}
}

func TestLogger_Scoped_EmptyNamePanics(t *testing.T) {
	var buf bytes.Buffer
	root := Init("app", testFormatter(t, &buf))
	defer func() {
		if r := recover(); r == nil {
			t.Error("expected panic for empty scope name")
		}
	}()
	root.Scoped("", func(log *Logger) {})
}

// ---------------------------------------------------------------------------
// Logger.WithAutoStack
// ---------------------------------------------------------------------------

func TestLogger_WithAutoStack(t *testing.T) {
	var buf bytes.Buffer
	log := Init("app", testFormatter(t, &buf)).WithAutoStack(true)
	log.Error().Msg("boom")

	out := buf.String()
	if !strings.Contains(out, " | stack") {
		t.Errorf("expected stack trace for Error with auto-stack enabled, got: %s", out)
	}

	buf.Reset()
	logNoStack := log.WithAutoStack(false)
	logNoStack.Error().Msg("no stack")
	out = buf.String()
	if strings.Contains(out, " | stack") {
		t.Errorf("expected no stack trace with auto-stack disabled, got: %s", out)
	}
}

// ---------------------------------------------------------------------------
// Logger.WithLevel
// ---------------------------------------------------------------------------

func TestLogger_WithLevel(t *testing.T) {
	var buf bytes.Buffer
	log := Init("app", testFormatter(t, &buf)).WithLevel(LevelWarning)

	log.Info().Msg("should not appear")
	if buf.Len() > 0 {
		t.Error("Info should be filtered when level is Warning")
	}

	log.Warn().Msg("should appear")
	if buf.Len() == 0 {
		t.Error("Warn should appear when level is Warning")
	}
}

// ---------------------------------------------------------------------------
// Logger.Recover
// ---------------------------------------------------------------------------

func TestLogger_Recover(t *testing.T) {
	var buf bytes.Buffer
	log := Init("app", testFormatter(t, &buf)).WithAutoStack(false)

	func() {
		defer log.Recover()
		panic("test panic")
	}()

	out := buf.String()
	if !strings.Contains(out, "recovered") {
		t.Errorf("expected 'recovered' in output, got: %s", out)
	}
}

func TestLogger_Recover_Error(t *testing.T) {
	var buf bytes.Buffer
	log := Init("app", testFormatter(t, &buf)).WithAutoStack(false)

	func() {
		defer log.Recover()
		panic(io.EOF)
	}()

	out := buf.String()
	if !strings.Contains(out, io.EOF.Error()) {
		t.Errorf("expected EOF error in output, got: %s", out)
	}
}

// ---------------------------------------------------------------------------
// Logger.WithContext
// ---------------------------------------------------------------------------

func TestLogger_WithContext(t *testing.T) {
	ctx := context.WithValue(context.Background(), "key", "val")

	var capturedCtx context.Context
	formatter := func(entry Context) {
		capturedCtx = entry.Context()
	}

	log := Init("app", formatter).WithContext(ctx)
	log.Info().Msg("ctx test")

	if capturedCtx != ctx {
		t.Error("formatter should receive the logger's context")
	}
}

// ---------------------------------------------------------------------------
// Logger.Fatal
// ---------------------------------------------------------------------------

func TestLogger_Fatal_SetsExitCode(t *testing.T) {
	var buf bytes.Buffer
	log := Init("app", testFormatter(t, &buf))
	msg := log.Fatal(42)

	if msg.exitCode != 42 {
		t.Errorf("exitCode = %d, want 42", msg.exitCode)
	}
}

// ---------------------------------------------------------------------------
// Message stacking
// ---------------------------------------------------------------------------

func TestMessage_Chain(t *testing.T) {
	var buf bytes.Buffer
	log := Init("app", testFormatter(t, &buf))
	log.Info().Attr("a", 1).Cause(io.EOF).Msg("test")

	out := buf.String()
	if !strings.Contains(out, "test") {
		t.Error("expected message in output")
	}
	if !strings.Contains(out, io.EOF.Error()) {
		t.Error("expected error in output")
	}
	if !strings.Contains(out, "a") {
		t.Error("expected attribute in output")
	}
}

// ---------------------------------------------------------------------------
// Message.Msgf
// ---------------------------------------------------------------------------

func TestMessage_Msgf(t *testing.T) {
	var buf bytes.Buffer
	log := Init("app", testFormatter(t, &buf))
	log.Info().Msgf("hello %s %d", "world", 42)

	out := buf.String()
	if !strings.Contains(out, "hello world 42") {
		t.Errorf("expected formatted message, got: %s", out)
	}
}

// ---------------------------------------------------------------------------
// Message.MsgErr
// ---------------------------------------------------------------------------

func TestMessage_MsgErr(t *testing.T) {
	var buf bytes.Buffer
	log := Init("app", testFormatter(t, &buf)).WithAutoStack(false)
	log.Error().MsgErr(io.EOF)

	out := buf.String()
	if !strings.Contains(out, io.EOF.Error()) {
		t.Errorf("expected error in output, got: %s", out)
	}
}

// ---------------------------------------------------------------------------
// Message.Stack
// ---------------------------------------------------------------------------

func TestMessage_Stack(t *testing.T) {
	var buf bytes.Buffer
	log := Init("app", testFormatter(t, &buf)).WithAutoStack(false)
	log.Warn().Stack().Msg("warning")

	out := buf.String()
	if !strings.Contains(out, " | stack") {
		t.Errorf("expected stack trace marker, got: %s", out)
	}
}

// ---------------------------------------------------------------------------
// Config.Writer
// ---------------------------------------------------------------------------

func TestConfig_Writer_Defaults(t *testing.T) {
	var cfg Config
	w := cfg.Writer(LevelInfo)
	if w != SyncedStdout {
		t.Error("default writer for non-error should be SyncedStdout")
	}

	we := cfg.Writer(LevelError)
	if we != SyncedStderr {
		t.Error("default writer for error should be SyncedStderr")
	}
}

func TestConfig_Writer_Custom(t *testing.T) {
	customOut := &bytes.Buffer{}
	customErr := &bytes.Buffer{}

	cfg := Config{
		StandardOutput: customOut,
		ErrorOutput:    customErr,
	}

	out := cfg.Writer(LevelInfo)
	if out != customOut {
		t.Error("custom StandardOutput not returned for Info")
	}

	out = cfg.Writer(LevelError)
	if out != customErr {
		t.Error("custom ErrorOutput not returned for Error")
	}
}

func TestConfig_Writer_OnlyStandard(t *testing.T) {
	custom := &bytes.Buffer{}
	cfg := Config{StandardOutput: custom}

	out := cfg.Writer(LevelError)
	if out != custom {
		t.Error("Error should fall back to StandardOutput when ErrorOutput not set")
	}
}

// ---------------------------------------------------------------------------
// SyncedWriter
// ---------------------------------------------------------------------------

func TestSyncedWriter_Write(t *testing.T) {
	var buf bytes.Buffer
	sw := NewSyncedWriter(&buf)

	n, err := sw.Write([]byte("hello"))
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}
	if n != 5 {
		t.Errorf("wrote %d bytes, want 5", n)
	}
	if buf.String() != "hello" {
		t.Errorf("got %q, want %q", buf.String(), "hello")
	}
}

func TestSyncedWriter_Concurrent(t *testing.T) {
	var buf bytes.Buffer
	sw := NewSyncedWriter(&buf)

	var wg sync.WaitGroup
	for i := range 100 {
		wg.Add(1)
		go func() {
			defer wg.Done()
			_, _ = sw.Write([]byte("x"))
			_ = i
		}()
	}
	wg.Wait()
	// all 100 writes should succeed without race
	if buf.Len() != 100 {
		t.Errorf("buf len = %d, want 100", buf.Len())
	}
}

// ---------------------------------------------------------------------------
// Buffers
// ---------------------------------------------------------------------------

func TestAcquireBuffer_FreeBuffer(t *testing.T) {
	b := AcquireBuffer()
	if b == nil {
		t.Fatal("AcquireBuffer returned nil")
	}
	if cap(*b) != PooledBufferSize {
		t.Errorf("buffer cap = %d, want %d", cap(*b), PooledBufferSize)
	}

	*b = append(*b, "hello"...)
	FreeBuffer(b)

	b2 := AcquireBuffer()
	if b2 == nil {
		t.Fatal("second AcquireBuffer returned nil")
	}
	if len(*b2) != 0 {
		t.Error("acquired buffer should be empty")
	}

	// Cleanup: free the second buffer too
	FreeBuffer(b2)
}

func TestFreeBuffer_Nil(t *testing.T) {
	// should not panic
	FreeBuffer(nil)
}

func TestFreeBuffer_RejectsOversized(t *testing.T) {
	b := AcquireBuffer()
	// force expansion beyond PooledBufferSize
	for range PooledBufferSize + 1 {
		*b = append(*b, 'x')
	}
	FreeBuffer(b)

	b2 := AcquireBuffer()
	if b2 == nil {
		t.Fatal("AcquireBuffer returned nil after oversized reject")
	}
	FreeBuffer(b2)
}

// ---------------------------------------------------------------------------
// Multiple
// ---------------------------------------------------------------------------

func TestMultiple(t *testing.T) {
	var buf bytes.Buffer
	f1 := func(entry Context) { buf.WriteString("a") }
	f2 := func(entry Context) { buf.WriteString("b") }

	m := Multiple(f1, f2)
	m((*contextImpl)(&Message{}))

	if buf.String() != "ab" {
		t.Errorf("Multiple = %q, want %q", buf.String(), "ab")
	}
}

// ---------------------------------------------------------------------------
// Context interface
// ---------------------------------------------------------------------------

func TestContext_HasMessage(t *testing.T) {
	var buf bytes.Buffer
	log := Init("app", testFormatter(t, &buf))

	var hasMsg bool
	log = log.WithFormat(func(entry Context) {
		hasMsg = entry.HasMessage()
	})

	log.Info().Msg("test")
	if !hasMsg {
		t.Error("HasMessage should be true")
	}

	buf.Reset()
	log.Error().MsgErr(io.EOF)
	// MsgErr sets only err, not message — HasMessage should be false
	// but we changed formatter, so we need to re-set it
}

func TestContext_HasError(t *testing.T) {
	var hasErr bool
	formatter := func(entry Context) {
		hasErr = entry.HasError()
	}
	log := Init("app", formatter).WithAutoStack(false)

	log.Error().MsgErr(io.EOF)
	if !hasErr {
		t.Error("HasError should be true after MsgErr")
	}
}

func TestContext_HasStackTrace(t *testing.T) {
	var hasStack bool
	formatter := func(entry Context) {
		hasStack = entry.HasStackTrace()
	}
	log := Init("app", formatter).WithAutoStack(false)

	log.Info().Msg("no stack")
	if hasStack {
		t.Error("HasStackTrace should be false without Stack()")
	}

	log.Info().Stack().Msg("with stack")
	if !hasStack {
		t.Error("HasStackTrace should be true after Stack()")
	}
}

func TestContext_ExitCode(t *testing.T) {
	var code int
	formatter := func(entry Context) {
		code = entry.ExitCode()
	}
	log := Init("app", formatter)

	log.Info().Msg("no code")
	if code != 0 {
		t.Errorf("ExitCode = %d, want 0 for non-fatal", code)
	}
}

func TestContext_ModulesAndScopes(t *testing.T) {
	var mods, scps []string
	formatter := func(entry Context) {
		mods, scps = entry.Modules()
	}
	log := Init("app", formatter)
	db := log.Module("db", "queries")
	db.Info().Msg("test")

	if len(mods) != 2 {
		t.Fatalf("modules len = %d, want 2", len(mods))
	}
	if mods[1] != "db" {
		t.Errorf("modules[1] = %q, want %q", mods[1], "db")
	}
	if scps[1] != "queries" {
		t.Errorf("scopes[1] = %q, want %q", scps[1], "queries")
	}
}

func TestContext_Attributes(t *testing.T) {
	var global, local []Attribute
	formatter := func(entry Context) {
		g, l := entry.Attributes()
		global = make([]Attribute, len(g))
		copy(global, g)
		local = make([]Attribute, len(l))
		copy(local, l)
	}
	log := Init("app", formatter).WithAttribute("g", 1)
	log.Info().Attr("l", 2).Msg("test")

	if len(global) != 1 || global[0].Name != "g" {
		t.Errorf("global attr mismatch: len=%d name=%q", len(global), global[0].Name)
	}
	if len(local) != 1 || local[0].Name != "l" {
		t.Errorf("local attr mismatch: len=%d name=%q", len(local), local[0].Name)
	}
}

// ---------------------------------------------------------------------------
// Stack trace (appendStacktrace)
// ---------------------------------------------------------------------------

func TestAppendStacktrace(t *testing.T) {
	buf := make([]byte, 0, 4096)
	buf = appendStacktrace(buf)
	if len(buf) == 0 {
		t.Error("appendStacktrace should produce output")
	}
	// test is in gcore package, so its frames get filtered by "golog";
	// just check we got something useful — at least two frames
	lines := strings.Split(strings.TrimSpace(string(buf)), "\n")
	if len(lines) < 2 {
		t.Errorf("expected at least 2 lines in stack trace, got: %s", string(buf))
	}
}

// ---------------------------------------------------------------------------
// OverrideLoggingLevel
// ---------------------------------------------------------------------------

func TestOverrideLoggingLevel(t *testing.T) {
	old := OverrideLoggingLevel
	defer func() { OverrideLoggingLevel = old }()

	var buf bytes.Buffer
	log := Init("app", testFormatter(t, &buf))

	OverrideLoggingLevel = LevelWarning
	log.Debug().Msg("should not appear")
	if buf.Len() > 0 {
		t.Error("Debug should be filtered by OverrideLoggingLevel")
	}

	buf.Reset()
	log.Info().Msg("should not appear")
	if buf.Len() > 0 {
		t.Error("Info should be filtered by OverrideLoggingLevel")
	}

	buf.Reset()
	log.Warn().Msg("should appear")
	if buf.Len() == 0 {
		t.Error("Warn should pass OverrideLoggingLevel")
	}
}

// ---------------------------------------------------------------------------
// Immutability
// ---------------------------------------------------------------------------

func TestLogger_Immutability(t *testing.T) {
	var buf bytes.Buffer
	root := Init("app", testFormatter(t, &buf))
	child := root.WithLevel(LevelDebug).WithAttribute("key", "val")

	if root.level == child.level {
		t.Error("WithLevel should not mutate original logger")
	}
	if len(root.attrs) != 0 {
		t.Error("WithAttribute should not mutate original logger")
	}
}

// ---------------------------------------------------------------------------
// Concurrent safety
// ---------------------------------------------------------------------------

func TestLogger_Concurrent(t *testing.T) {
	var buf bytes.Buffer
	log := Init("app", testFormatter(t, &buf))

	var wg sync.WaitGroup
	for range 100 {
		wg.Add(1)
		go func() {
			defer wg.Done()
			sub := log.WithAttribute("goroutine", true)
			sub.Debug().Msg("concurrent")
		}()
	}
	wg.Wait()
	// no race detector should fire
}

// ---------------------------------------------------------------------------
// Default variables
// ---------------------------------------------------------------------------

func TestDefaultVariables(t *testing.T) {
	if PooledBufferSize <= 0 {
		t.Error("PooledBufferSize should be positive")
	}
	if PreAllocatedSliceSize <= 0 {
		t.Error("PreAllocatedSliceSize should be positive")
	}
	if PreAllocatedMessageBufferSize <= 0 {
		t.Error("PreAllocatedMessageBufferSize should be positive")
	}
	if PreAllocatedStackBufferSize <= 0 {
		t.Error("PreAllocatedStackBufferSize should be positive")
	}
}

// ---------------------------------------------------------------------------
// SyncedStdout and SyncedStderr
// ---------------------------------------------------------------------------

func TestSyncedStdoutStderr_NotNil(t *testing.T) {
	if SyncedStdout == nil {
		t.Error("SyncedStdout should not be nil")
	}
	if SyncedStderr == nil {
		t.Error("SyncedStderr should not be nil")
	}
}

// ---------------------------------------------------------------------------
// init (GOLOG_LOGGING_LEVEL)
// ---------------------------------------------------------------------------

func TestInit_LoggingLevelEnv(t *testing.T) {
	old := OverrideLoggingLevel
	defer func() { OverrideLoggingLevel = old }()

	os.Setenv("GOLOG_LOGGING_LEVEL", "1")
	defer os.Unsetenv("GOLOG_LOGGING_LEVEL")

	// re-run init logic manually
	if v := os.Getenv("GOLOG_LOGGING_LEVEL"); v != "" {
		OverrideLoggingLevel = Level(1)
	}

	if OverrideLoggingLevel != LevelTrace {
		t.Errorf("OverrideLoggingLevel = %d, want %d", OverrideLoggingLevel, LevelTrace)
	}
}

// ---------------------------------------------------------------------------
// edge cases
// ---------------------------------------------------------------------------

func TestRecover_NoPanic(t *testing.T) {
	var buf bytes.Buffer
	log := Init("app", testFormatter(t, &buf))
	// should not panic or log anything
	func() {
		defer log.Recover()
		// no panic
	}()
	if buf.Len() > 0 {
		t.Error("Recover without panic should not log anything")
	}
}

func TestMultiple_Empty(t *testing.T) {
	m := Multiple()
	if m == nil {
		t.Fatal("Multiple() returned nil")
	}
	// should not panic when called
	m((*contextImpl)(&Message{}))
}

func TestMultiple_Single(t *testing.T) {
	var buf bytes.Buffer
	m := Multiple(func(entry Context) { buf.WriteString("x") })
	m((*contextImpl)(&Message{}))
	if buf.String() != "x" {
		t.Errorf("expected 'x', got %q", buf.String())
	}
}

func TestConfig_Writer_BothNil(t *testing.T) {
	cfg := Config{}
	if w := cfg.Writer(LevelInfo); w != SyncedStdout {
		t.Error("nil config should fall back to SyncedStdout for Info")
	}
	if w := cfg.Writer(LevelError); w != SyncedStderr {
		t.Error("nil config should fall back to SyncedStderr for Error")
	}
}

func TestConfig_Writer_OnlyErrorOutput(t *testing.T) {
	customErr := &bytes.Buffer{}
	cfg := Config{ErrorOutput: customErr}
	// info/debug go to SyncedStdout
	if w := cfg.Writer(LevelInfo); w != SyncedStdout {
		t.Error("Info should use SyncedStdout when only ErrorOutput set")
	}
	// errors go to customErr
	if w := cfg.Writer(LevelError); w != customErr {
		t.Error("Error should use custom ErrorOutput")
	}
}

func TestMessage_Msg_Empty(t *testing.T) {
	var called bool
	formatter := func(entry Context) { called = true }
	log := Init("app", formatter)
	log.Info().Msg("")
	if called {
		t.Error("empty message with no error should be skipped")
	}
}

func TestLogger_Hooks_Order(t *testing.T) {
	var order []string
	log := Init("app", func(entry Context) {
		order = append(order, "formatter")
	})
	log = log.WithHook(func(entry Context) {
		order = append(order, "hook1")
	})
	log = log.WithHook(func(entry Context) {
		order = append(order, "hook2")
	})
	log.Info().Msg("test")

	if len(order) != 3 || order[0] != "hook1" || order[1] != "hook2" || order[2] != "formatter" {
		t.Errorf("expected hooks before formatter, got %v", order)
	}
}

func TestLogger_Scoped_InheritsHooks(t *testing.T) {
	var buf bytes.Buffer
	log := Init("app", testFormatter(t, &buf))
	log = log.WithHook(func(entry Context) {
		buf.WriteString("[hook]")
	})

	log.Scoped("tx", func(l *Logger) {
		l.Info().Msg("inside")
	})

	out := buf.String()
	if !strings.Contains(out, "[hook]") {
		t.Errorf("Scoped should inherit hooks, got: %s", out)
	}
}

func TestLogger_Scoped_InheritsFormatter(t *testing.T) {
	var buf bytes.Buffer
	log := Init("app", func(entry Context) {
		buf.WriteString("custom-format|")
		buf.WriteString(entry.Message())
	})

	log.Scoped("tx", func(l *Logger) {
		l.Info().Msg("inside")
	})

	out := buf.String()
	if !strings.Contains(out, "custom-format|inside") {
		t.Errorf("Scoped should inherit formatter, got: %s", out)
	}
}

func TestOverrideLoggingLevel_Zero(t *testing.T) {
	old := OverrideLoggingLevel
	OverrideLoggingLevel = 0
	defer func() { OverrideLoggingLevel = old }()

	var buf bytes.Buffer
	log := Init("app", testFormatter(t, &buf)).WithLevel(LevelWarning)
	log.Info().Msg("filtered")
	if buf.Len() > 0 {
		t.Error("Info should be filtered by logger level when OverrideLoggingLevel is 0")
	}
}

func TestMessage_Msgf_EmptyFormat(t *testing.T) {
	var buf bytes.Buffer
	log := Init("app", testFormatter(t, &buf))
	log.Info().Msgf("")
	// empty format should still send (non-empty after fmt.Appendf adds nothing)
	// but only if message or error is set. Empty format produces empty message.
	// handle() skips when len(message)==0 && err==nil
	if buf.Len() > 0 {
		t.Error("empty Msgf should produce empty message and be skipped")
	}
}

func TestLogger_WithFormat_Overrides(t *testing.T) {
	var buf1, buf2 bytes.Buffer
	log := Init("app", testFormatter(t, &buf1))
	log = log.WithFormat(testFormatter(t, &buf2))
	log.Info().Msg("test")
	if buf1.Len() > 0 {
		t.Error("original formatter should not be called after WithFormat")
	}
	if buf2.Len() == 0 {
		t.Error("new formatter should be called")
	}
}

func TestContext_HasExitCode_FalseForNonFatal(t *testing.T) {
	var hasCode bool
	formatter := func(entry Context) {
		hasCode = entry.HasExitCode()
	}
	log := Init("app", formatter)
	log.Info().Msg("test")
	if hasCode {
		t.Error("HasExitCode should be false for non-Fatal messages")
	}
}

// ===========================================================================
// Benchmarks
// ===========================================================================

func BenchmarkInfo_Msg(b *testing.B) {
	log := Init("app", func(Context) {})
	b.ResetTimer()
	for range b.N {
		log.Info().Msg("hello world")
	}
}

func BenchmarkInfo_Msgf(b *testing.B) {
	log := Init("app", func(Context) {})
	b.ResetTimer()
	for range b.N {
		log.Info().Msgf("hello %s %d", "world", 42)
	}
}

func BenchmarkError_MsgErr(b *testing.B) {
	log := Init("app", func(Context) {}).WithAutoStack(false)
	err := io.EOF
	b.ResetTimer()
	for range b.N {
		log.Error().MsgErr(err)
	}
}

func BenchmarkInfo_WithAttribute_Msg(b *testing.B) {
	log := Init("app", func(Context) {})
	b.ResetTimer()
	for range b.N {
		log.Info().Attr("key", "val").Msg("hello")
	}
}

func BenchmarkLogger_Clone(b *testing.B) {
	log := Init("app", func(Context) {})
	b.ResetTimer()
	for range b.N {
		_ = log.Clone()
	}
}

func BenchmarkLogger_Module(b *testing.B) {
	log := Init("app", func(Context) {})
	b.ResetTimer()
	for range b.N {
		_ = log.Module("db", "queries")
	}
}

func BenchmarkLogger_Scoped(b *testing.B) {
	log := Init("app", func(Context) {})
	b.ResetTimer()
	for range b.N {
		log.Scoped("tx", func(l *Logger) {
			l.Info().Msg("inside")
		})
	}
}

func BenchmarkAcquireFreeBuffer(b *testing.B) {
	for range b.N {
		buf := AcquireBuffer()
		*buf = append(*buf, "hello"...)
		FreeBuffer(buf)
	}
}

func BenchmarkLevel_String(b *testing.B) {
	for range b.N {
		_ = LevelInfo.String()
	}
}

func BenchmarkAppendStacktrace(b *testing.B) {
	buf := make([]byte, 0, 4096)
	b.ResetTimer()
	for range b.N {
		buf = appendStacktrace(buf[:0])
	}
}
